### PR TITLE
Add: pipenv replace for requirement and test-requirement

### PR DESCRIPTION
**Pull request by b3g00d**

### CODE REVIEW

**Comment by destag** [comment]
Hi @b3g00d! Thank you very much for this PR. 

I see there were some problems with dependencies.  In the future I will probably try to replace multiple jobs with matrix.

Could you also delete **.coverage** file? Because I left it by mistake.

If you have any questions feel free to ask.

**Comment by b3g00d** [comment]
@destag Becareful with new version of pip 18.1 and pipenv. https://github.com/pypa/pipenv/issues/2924

**Comment by destag** [comment]
@b3g00d Thanks for info. 

I see people try to workaround this by ```pipenv install pip==18.0```. Travis uses pip==9.0.1 for this project, but I will keep this in mind.

You added dashes (-) to .coveragerc by mistake

**Comment by b3g00d** [comment]
@destag my mistake when tried restore `coveragerc` file.

**Pull request merged**
